# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Path to old blog posts:
# C:\Users\Wouter\Dropbox\Personal\Blogging

# Site settings
# Accessed via {{ site.title }}
title: Something Fishy
author: Van Schandevijl Wouter
email: woutervs@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Laoujin
google_analytics: UA-30075487-6

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
