# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Path to old blog posts:
# C:\Users\Wouter\Dropbox\Personal\Blogging

# Site settings
# Accessed via {{ site.title }}
title: Something Fishy
author: Van Schandevijl Wouter
logo: /favicon.png
email: wouter@pongit.be
telephone: +32 (0)476 / 40 35 02
description: > # this means to ignore newlines until "baseurl:"
  Programming and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pongit.be" # the base hostname & protocol for your site, e.g. http://example.com
#repository: Laoujin/bliki
github_data_url: https://github.com/itenium-be/blog-posts/blob/master
github_username: Laoujin
google_analytics: UA-30075487-6
excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /:path/
  bliki:
    output: true
    permalink: /:path/

jekyll-archives:
  enabled: # all
    - categories
    - tags
  layout: pages/archive
  # layouts:
  #   category: archives/category
  #   tag: archives/category
  #   year: archives/year
  #   month: archives/month
  #   day: archives/month
  permalinks:
    category: '/:name/'
    tag: '/tags/:name/'
    year: '/:year/'
    month: '/:year/:month/'

# Build settings
markdown: kramdown
#lsi: true # https://jekyllrb.com/docs/configuration/
theme: jekyll-theme-minimal
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-feed
#  - jekyll-archives

kramdown:
#   parse_block_html: true
#   input: GFM
#   hard_wrap: false
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
  toc_levels: 1..3
#   smart_quotes: lsquo,rsquo,ldquo,rdquo
#   enable_coderay: false


exclude:
  - Gemfile
  - Gemfile.lock
  - rvm-installer
  - LICENSE
  - package.json
  - TODO.md
  - README.md
