# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Accessed via {{ site.title }}
title: Something Fishy
author: Van Schandevijl Wouter
email: wouter@pongit.be
telephone: +32 (0)476 / 40 35 02
description: >
  Programming and stuff
baseurl: ""
url: "https://pongit.be"
github_username: Laoujin
google_analytics: UA-30075487-6

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - rvm-installer
  - LICENSE
  - package.json
  - README.md
