# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Path to old blog posts:
# C:\Users\Wouter\Dropbox\Personal\Blogging

# Site settings
# Accessed via {{ site.title }}
title: Something Fishy
author: Van Schandevijl Wouter
logo: /favicon.png
email: woutervs@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Programming and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#repository: be-pongit/be-pongit.github.io
github_username: Laoujin
google_analytics: UA-30075487-6
excerpt_separator: <!--more-->

jekyll-archives:
  enabled: [category, tag, year, month]
  layouts:
    category: archives/category
    year: archives/year
    month: archives/month
    tag: archives/category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'


# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - package.json
